<?php

namespace Raakkan\PhpTailwind\Tailwind\Static;

class FlexGridClasses
{
    public static function getClasses(): array
    {
        return [
            'flex-row' => '.flex-row{flex-direction:row;}',
            'flex-col' => '.flex-col{flex-direction:column;}',
            'flex-row-reverse' => '.flex-row-reverse{flex-direction:row-reverse;}',
            'flex-col-reverse' => '.flex-col-reverse{flex-direction:column-reverse;}',
            'flex-wrap' => '.flex-wrap{flex-wrap:wrap;}',
            'flex-wrap-reverse' => '.flex-wrap-reverse{flex-wrap:wrap-reverse;}',
            'flex-nowrap' => '.flex-nowrap{flex-wrap:nowrap;}',
            'grid-flow-row' => '.grid-flow-row{grid-auto-flow:row;}',
            'grid-flow-col' => '.grid-flow-col{grid-auto-flow:column;}',
            'grid-flow-dense' => '.grid-flow-dense{grid-auto-flow:dense;}',
            'grid-flow-row-dense' => '.grid-flow-row-dense{grid-auto-flow:row dense;}',
            'grid-flow-col-dense' => '.grid-flow-col-dense{grid-auto-flow:column dense;}',
            'justify-normal' => '.justify-normal{justify-content:normal;}',
            'justify-start' => '.justify-start{justify-content:flex-start;}',
            'justify-end' => '.justify-end{justify-content:flex-end;}',
            'justify-center' => '.justify-center{justify-content:center;}',
            'justify-between' => '.justify-between{justify-content:space-between;}',
            'justify-around' => '.justify-around{justify-content:space-around;}',
            'justify-evenly' => '.justify-evenly{justify-content:space-evenly;}',
            'justify-stretch' => '.justify-stretch{justify-content:stretch;}',
            'justify-items-start' => '.justify-items-start{justify-items:start;}',
            'justify-items-end' => '.justify-items-end{justify-items:end;}',
            'justify-items-center' => '.justify-items-center{justify-items:center;}',
            'justify-items-stretch' => '.justify-items-stretch{justify-items:stretch;}',
            'justify-self-auto' => '.justify-self-auto{justify-self:auto;}',
            'justify-self-start' => '.justify-self-start{justify-self:start;}',
            'justify-self-end' => '.justify-self-end{justify-self:end;}',
            'justify-self-center' => '.justify-self-center{justify-self:center;}',
            'justify-self-stretch' => '.justify-self-stretch{justify-self:stretch;}',
            'content-normal' => '.content-normal{align-content:normal;}',
            'content-center' => '.content-center{align-content:center;}',
            'content-start' => '.content-start{align-content:flex-start;}',
            'content-end' => '.content-end{align-content:flex-end;}',
            'content-between' => '.content-between{align-content:space-between;}',
            'content-around' => '.content-around{align-content:space-around;}',
            'content-evenly' => '.content-evenly{align-content:space-evenly;}',
            'content-baseline' => '.content-baseline{align-content:baseline;}',
            'content-stretch' => '.content-stretch{align-content:stretch;}',
            'items-start' => '.items-start{align-items:flex-start;}',
            'items-end' => '.items-end{align-items:flex-end;}',
            'items-center' => '.items-center{align-items:center;}',
            'items-baseline' => '.items-baseline{align-items:baseline;}',
            'items-stretch' => '.items-stretch{align-items:stretch;}',
            'self-auto' => '.self-auto{align-self:auto;}',
            'self-start' => '.self-start{align-self:flex-start;}',
            'self-end' => '.self-end{align-self:flex-end;}',
            'self-center' => '.self-center{align-self:center;}',
            'self-stretch' => '.self-stretch{align-self:stretch;}',
            'self-baseline' => '.self-baseline{align-self:baseline;}',
            'place-content-center' => '.place-content-center{place-content:center;}',
            'place-content-start' => '.place-content-start{place-content:start;}',
            'place-content-end' => '.place-content-end{place-content:end;}',
            'place-content-between' => '.place-content-between{place-content:space-between;}',
            'place-content-around' => '.place-content-around{place-content:space-around;}',
            'place-content-evenly' => '.place-content-evenly{place-content:space-evenly;}',
            'place-content-baseline' => '.place-content-baseline{place-content:baseline;}',
            'place-content-stretch' => '.place-content-stretch{place-content:stretch;}',
            'place-items-start' => '.place-items-start{place-items:start;}',
            'place-items-end' => '.place-items-end{place-items:end;}',
            'place-items-center' => '.place-items-center{place-items:center;}',
            'place-items-baseline' => '.place-items-baseline{place-items:baseline;}',
            'place-items-stretch' => '.place-items-stretch{place-items:stretch;}',
            'place-self-auto' => '.place-self-auto{place-self:auto;}',
            'place-self-start' => '.place-self-start{place-self:start;}',
            'place-self-end' => '.place-self-end{place-self:end;}',
            'place-self-center' => '.place-self-center{place-self:center;}',
            'place-self-stretch' => '.place-self-stretch{place-self:stretch;}',
        ];
    }
}
