<?php

namespace Raakkan\PhpTailwind\Tailwind\Static;

class LayoutClasses
{
    public static function getClasses(): array
    {
        return [
            'break-after-auto' => '.break-after-auto{break-after:auto;}',
            'break-after-avoid' => '.break-after-avoid{break-after:avoid;}',
            'break-after-all' => '.break-after-all{break-after:all;}',
            'break-after-avoid-page' => '.break-after-avoid-page{break-after:avoid-page;}',
            'break-after-page' => '.break-after-page{break-after:page;}',
            'break-after-left' => '.break-after-left{break-after:left;}',
            'break-after-right' => '.break-after-right{break-after:right;}',
            'break-after-column' => '.break-after-column{break-after:column;}',
            'break-before-auto' => '.break-before-auto{break-before:auto;}',
            'break-before-avoid' => '.break-before-avoid{break-before:avoid;}',
            'break-before-all' => '.break-before-all{break-before:all;}',
            'break-before-avoid-page' => '.break-before-avoid-page{break-before:avoid-page;}',
            'break-before-page' => '.break-before-page{break-before:page;}',
            'break-before-left' => '.break-before-left{break-before:left;}',
            'break-before-right' => '.break-before-right{break-before:right;}',
            'break-before-column' => '.break-before-column{break-before:column;}',
            'break-inside-auto' => '.break-inside-auto{break-inside:auto;}',
            'break-inside-avoid' => '.break-inside-avoid{break-inside:avoid;}',
            'break-inside-avoid-page' => '.break-inside-avoid-page{break-inside:avoid-page;}',
            'break-inside-avoid-column' => '.break-inside-avoid-column{break-inside:avoid-column;}',
            'box-decoration-clone' => '.box-decoration-clone{box-decoration-break:clone;}',
            'box-decoration-slice' => '.box-decoration-slice{box-decoration-break:slice;}',
            'box-border' => '.box-border{box-sizing:border-box;}',
            'box-content' => '.box-content{box-sizing:content-box;}',
            'block' => '.block{display:block;}',
            'inline-block' => '.inline-block{display:inline-block;}',
            'inline' => '.inline{display:inline;}',
            'flex' => '.flex{display:flex;}',
            'inline-flex' => '.inline-flex{display:inline-flex;}',
            'table' => '.table{display:table;}',
            'inline-table' => '.inline-table{display:inline-table;}',
            'table-caption' => '.table-caption{display:table-caption;}',
            'table-cell' => '.table-cell{display:table-cell;}',
            'table-column' => '.table-column{display:table-column;}',
            'table-column-group' => '.table-column-group{display:table-column-group;}',
            'table-footer-group' => '.table-footer-group{display:table-footer-group;}',
            'table-header-group' => '.table-header-group{display:table-header-group;}',
            'table-row-group' => '.table-row-group{display:table-row-group;}',
            'table-row' => '.table-row{display:table-row;}',
            'flow-root' => '.flow-root{display:flow-root;}',
            'grid' => '.grid{display:grid;}',
            'inline-grid' => '.inline-grid{display:inline-grid;}',
            'contents' => '.contents{display:contents;}',
            'list-item' => '.list-item{display:list-item;}',
            'hidden' => '.hidden{display:none;}',
            'float-start' => '.float-start{float:inline-start;}',
            'float-end' => '.float-end{float:inline-end;}',
            'float-right' => '.float-right{float:right;}',
            'float-left' => '.float-left{float:left;}',
            'float-none' => '.float-none{float:none;}',
            'clear-start' => '.clear-start{clear:inline-start;}',
            'clear-end' => '.clear-end{clear:inline-end;}',
            'clear-left' => '.clear-left{clear:left;}',
            'clear-right' => '.clear-right{clear:right;}',
            'clear-both' => '.clear-both{clear:both;}',
            'clear-none' => '.clear-none{clear:none;}',
            'isolate' => '.isolate{isolation:isolate;}',
            'isolation-auto' => '.isolation-auto{isolation:auto;}',
            'object-contain' => '.object-contain{object-fit:contain;}',
            'object-cover' => '.object-cover{object-fit:cover;}',
            'object-fill' => '.object-fill{object-fit:fill;}',
            'object-none' => '.object-none{object-fit:none;}',
            'object-scale-down' => '.object-scale-down{object-fit:scale-down;}',
            'overflow-auto' => '.overflow-auto{overflow:auto;}',
            'overflow-hidden' => '.overflow-hidden{overflow:hidden;}',
            'overflow-clip' => '.overflow-clip{overflow:clip;}',
            'overflow-visible' => '.overflow-visible{overflow:visible;}',
            'overflow-scroll' => '.overflow-scroll{overflow:scroll;}',
            'overflow-x-auto' => '.overflow-x-auto{overflow-x:auto;}',
            'overflow-y-auto' => '.overflow-y-auto{overflow-y:auto;}',
            'overflow-x-hidden' => '.overflow-x-hidden{overflow-x:hidden;}',
            'overflow-y-hidden' => '.overflow-y-hidden{overflow-y:hidden;}',
            'overflow-x-clip' => '.overflow-x-clip{overflow-x:clip;}',
            'overflow-y-clip' => '.overflow-y-clip{overflow-y:clip;}',
            'overflow-x-visible' => '.overflow-x-visible{overflow-x:visible;}',
            'overflow-y-visible' => '.overflow-y-visible{overflow-y:visible;}',
            'overflow-x-scroll' => '.overflow-x-scroll{overflow-x:scroll;}',
            'overflow-y-scroll' => '.overflow-y-scroll{overflow-y:scroll;}',
            'overscroll-auto' => '.overscroll-auto{overscroll-behavior:auto;}',
            'overscroll-contain' => '.overscroll-contain{overscroll-behavior:contain;}',
            'overscroll-none' => '.overscroll-none{overscroll-behavior:none;}',
            'overscroll-y-auto' => '.overscroll-y-auto{overscroll-behavior-y:auto;}',
            'overscroll-y-contain' => '.overscroll-y-contain{overscroll-behavior-y:contain;}',
            'overscroll-y-none' => '.overscroll-y-none{overscroll-behavior-y:none;}',
            'overscroll-x-auto' => '.overscroll-x-auto{overscroll-behavior-x:auto;}',
            'overscroll-x-contain' => '.overscroll-x-contain{overscroll-behavior-x:contain;}',
            'overscroll-x-none' => '.overscroll-x-none{overscroll-behavior-x:none;}',
            'static' => '.static{position:static;}',
            'fixed' => '.fixed{position:fixed;}',
            'absolute' => '.absolute{position:absolute;}',
            'relative' => '.relative{position:relative;}',
            'sticky' => '.sticky{position:sticky;}',
            'visible' => '.visible{visibility:visible;}',
            'invisible' => '.invisible{visibility:hidden;}',
            'collapse' => '.collapse{visibility:collapse;}',
        ];
    }
}